[package]
name = "ci2-async"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
futures.workspace = true
tracing.workspace = true
parking_lot = "0.12"
thread-control = "0.1.2"

ci2 = { path = "../ci2" }
machine-vision-formats.workspace = true
