[package]
name = "ci2-vimba"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vimba.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
machine-vision-formats.workspace = true
chrono.workspace = true
lazy_static.workspace = true
tempfile.workspace = true

vmbc-sys = "0.1"

ci2.workspace = true
ci2-vimba-types.workspace = true
strand-dynamic-frame.workspace = true

[dev-dependencies]
env_logger.workspace = true
anyhow.workspace = true
