[package]
name = "ffmpeg-writer"
version = "0.1.0"
edition = "2024"

[dependencies]
machine-vision-formats.workspace = true
convert-image.workspace = true
thiserror.workspace = true
y4m-writer.workspace = true
y4m.workspace = true
strand-dynamic-frame.workspace = true

[dev-dependencies]
eyre.workspace = true
tracing.workspace = true
env_logger.workspace = true
rusttype.workspace = true
ttf-firacode.workspace = true
image.workspace = true

font-drawing.workspace = true
