[package]
name = "strand-cam-types"
description = "Core types for camera control and configuration in the Strand Camera ecosystem"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["strand-cam", "camera", "utils"]

[dependencies]
serde.workspace = true
strand-cam-enum-iter.workspace = true
