[package]
name = "ads-apriltag"
license = "BSD-2-Clause"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
apriltag-sys = "0.1.3"

[dev-dependencies]
machine-vision-formats = "0.1"
convert-image = { path = "../convert-image" }
image = "0.23"
