[package]
name = "strand-http-video-streaming-types"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Type definitions for HTTP video streaming functionality in the Strand Camera ecosystem."
repository = "https://github.com/strawlab/strand-braid"

[dependencies]
serde.workspace = true

strand-bui-backend-session-types.workspace = true

[dev-dependencies]
serde_yaml.workspace = true
