[package]
name = "ci2"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
chrono.workspace = true
dyn-clone.workspace = true

machine-vision-formats.workspace = true
strand-cam-types.workspace = true
strand-dynamic-frame.workspace = true
