[package]
name = "tracking"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
adskalman.workspace = true
nalgebra.workspace = true
num-traits.workspace = true

[dev-dependencies]
approx.workspace = true
