[package]
name = "download-verify"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "3.0.9"
thiserror.workspace = true
sha2 = "0.10.2"
hex = "0.4"
