[package]
name = "strand-http-video-streaming"
version = "0.1.0"
authors = ["strawlab"]
edition = "2021"
rust-version = "1.76"

[dependencies]
thiserror.workspace = true
chrono.workspace = true
base64.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
serde_json.workspace = true
futures.workspace = true
machine-vision-formats.workspace = true
bytes.workspace = true
http-body.workspace = true
tracing.workspace = true

convert-image.workspace = true
strand-http-video-streaming-types.workspace = true
strand-dynamic-frame = { workspace = true, features = ["convert-image"] }
strand-cam-bui-types.workspace = true
event-stream-types.workspace = true
strand-bui-backend-session-types.workspace = true
