[package]
name = "parry-geom"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
parry2d-f64 = { workspace = true, features = ["default"] }
delaunator.workspace = true
nalgebra.workspace = true
