[package]
name = "nvenc"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynlink-cuda = { path = "dynlink-cuda" }
dynlink-nvidia-encode = { path = "dynlink-nvidia-encode" }
thiserror.workspace = true
