[package]
name = "flydra-mvg"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"
rust-version = "1.85"

[dependencies]
thiserror.workspace = true
tracing.workspace = true
num-traits.workspace = true
nalgebra.workspace = true
parry3d-f64.workspace = true
serde.workspace = true
serde-xml-rs.workspace = true
cam-geom.workspace = true
opencv-ros-camera.workspace = true
xml.workspace = true

braid-mvg.workspace = true
refraction.workspace = true

[dev-dependencies]
num-iter.workspace = true
approx.workspace = true
