[package]
name = "simple-obj-parse"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
nalgebra.workspace = true
ncollide3d = { workspace = true, features = ["default", "serde-serialize"] }
textured-tri-mesh.workspace = true
genmesh = "0.6"
obj.workspace = true
