[package]
name = "dump-frame"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
machine-vision-formats.workspace = true
openh264.workspace = true
image.workspace = true
y4m.workspace = true
tiff = "0.9.0"

convert-image.workspace = true
