[package]
name = "flydra-pt-detect-cfg"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2021"
rust-version = "1.76"
license = "MIT/Apache-2.0"

[dependencies]
flydra-feature-detector-types = { path = "../flydra-feature-detector-types" }
http-video-streaming-types = { path = "../../http-video-streaming/http-video-streaming-types" }
