[package]
name = "flydra-pt-detect-cfg"
description = "Default values for the flydra-feature-detector-types crate"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
flydra-feature-detector-types.workspace = true
strand-http-video-streaming-types.workspace = true
