[package]
name = "event-stream-types"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
uuid.workspace = true
serde.workspace = true
http.workspace = true
axum.workspace = true
http-body.workspace = true
bytes.workspace = true
tokio-stream.workspace = true
futures.workspace = true
tracing.workspace = true
mime.workspace = true

strand-bui-backend-session-types.workspace = true
