[package]
name = "braid-config-data"
version = "0.1.0"
edition = "2024"

[dependencies]
toml.workspace = true
shellexpand.workspace = true
thiserror.workspace = true
tracing.workspace = true

braid-types.workspace = true
serde.workspace = true
