[package]
name = "strand-cam-vimba"
version = "0.12.0-alpha.9" # braid release synchronized
edition = "2024"

[dependencies]
eyre.workspace = true
lazy_static.workspace = true
tracing.workspace = true

ipp-sys = { workspace = true, optional = true }

imops = { workspace = true, optional = true }
ci2-async.workspace = true
ci2-vimba.workspace = true

strand-cam.workspace = true

[features]
default = ["strand-cam/bundle_files"]
