[package]
name = "braidz-cli"
version =  "0.10.0-beta.0" # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
env_logger = "0.8"
serde_yaml = "0.8"
anyhow = "1.0"

braidz-parser = {path=".."}
