[package]
name = "braidz-cli"
version = "0.12.0-alpha.9"                       # braid release synchronized
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
clap.workspace = true
env-tracing-logger.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true

braidz-parser.workspace = true
