[package]
name = "bundle-adj"
version = "0.1.0"
edition = "2024"

[dependencies]
cam-geom.workspace = true
clap.workspace = true
levenberg-marquardt.workspace = true
braid-mvg = { workspace = true }
nalgebra.workspace = true
num-traits.workspace = true
opencv-ros-camera.workspace = true
re_sdk = { workspace = true, optional = true }
re_sdk_types = { workspace = true, optional = true }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
approx.workspace = true
rand = "0.8"
rand_distr = "0.4"

[features]
with-rerun = ["dep:re_sdk", "dep:re_sdk_types", "braid-mvg/rerun-io"]
