[package]
name = "opencv-calibrate"
license = "MIT/Apache-2.0"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]

[build-dependencies]
pkg-config = "0.3"
cc = "1.0"
