[package]
name = "dir2zip"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"
license = "MIT/Apache-2.0"

[dependencies]
anyhow.workspace = true

zip-or-dir.workspace = true
