[package]
name = "find-chessboard"
description = "find chessboard corners in an input image"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
opencv-calibrate.workspace = true
image.workspace = true
serde_yaml.workspace = true
clap.workspace = true
anyhow.workspace = true
