[package]
name = "pylon-cxx-rs"
description = "Rust wrapper of the Pylon libraries for Basler cameras"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"
repository = "https://github.com/strawlab/strand-braid"

[dependencies]
cxx = "0.4"

[build-dependencies]
cxx-build = "0.4"
