[package]
name = "refraction"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
simba = {version="0.5", default-features=false, features=["libm"]}
bisection-search = {path="../bisection-search"}
