[package]
name = "strand-cam-csv-config-types"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
chrono.workspace = true
serde = { version = "^1.0", features = ["derive"] }

flydra-feature-detector-types = { path = "../flydra-feature-detector/flydra-feature-detector-types", default-features = false }
