[package]
name = "bui-backend-session-demo"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
log = "0.4"
futures = "0.3"
hyper = "0.13.0"
tokio = {version="0.2", features=["full"]}
env_logger = "0.8"
bui-backend-types = "0.8"

bui-backend-session = {path=".."}
