[package]
name = "bui-backend-session-demo"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2021"
rust-version="1.60"

[dependencies]
log = "0.4"
futures = "0.3"
hyper = "0.14"
tokio = {version="1.0.1", features=["full"]}
env_logger = "0.8"
bui-backend-types = "0.8"

bui-backend-session = {path=".."}
