[package]
name = "flydra1-triggerbox"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
anyhow = "1.0"
serialport = "3"
log = "0.4"
byteorder = "1"
thread-control = "0.1"
serde = "1.0"
nalgebra = "0.28"
chrono = "0.4"
lstsq = "0.1"
structopt = "0.3"
env_logger = "0.8"
crossbeam-channel = "0.5"
