[package]
name = "strand-dynamic-frame"
description = "images from machine vision cameras used in Strand Camera"
version = "0.1.0"
repository = "https://github.com/strawlab/strand-braid"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"
keywords = ["strand-cam"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]


[dependencies]
machine-vision-formats = { workspace = true, features = ["std"] }

convert-image = { workspace = true, optional = true }
