[package]
name = "create-timelapse"
version = "0.1.0"
edition = "2024"
description = "create timelapse video from mp4 h264 source without transcoding"

[dependencies]
clap.workspace = true
indicatif.workspace = true
eyre.workspace = true
h264-reader.workspace = true
chrono.workspace = true

strand-cam-remote-control.workspace = true
mp4-writer = { workspace = true, features = ["nv-encode"] }
frame-source.workspace = true
env-tracing-logger.workspace = true
