[package]
name = "dynlink-nvidia-encode"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
libloading = "0.7.3"
dynlink-cuda = { path = "../dynlink-cuda" }
thiserror.workspace = true
