[package]
name = "flytrax-io"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
serde_yaml.workspace = true

strand-cam-csv-config-types = { path = "../../strand-cam-csv-config-types" }
