[package]
name = "camcal"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.29"
opencv-ros-camera = "0.11"
serde = {version="1.0", features=["derive"]}

opencv-calibrate = {path="../opencv-calibrate"}
