[package]
name = "fmf"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
machine-vision-formats.workspace = true
strand-dynamic-frame.workspace = true
byteorder.workspace = true
chrono.workspace = true
strand-datetime-conversion.workspace = true
thiserror.workspace = true
libflate.workspace = true
