[package]
name = "bg-movie-writer"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
tracing.workspace = true
chrono.workspace = true
thiserror.workspace = true

mp4-writer = { workspace = true, features = ["openh264-encode", "nv-encode"] }
machine-vision-formats.workspace = true
strand-cam-remote-control.workspace = true
nvenc.workspace = true
strand-dynamic-frame.workspace = true

ffmpeg-rewriter.workspace = true
ffmpeg-writer.workspace = true
serde.workspace = true
serde_json.workspace = true
